CREATE TABLE IF NOT EXISTS companies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    company_name VARCHAR(200) NOT NULL,
    company_url_profile VARCHAR(200) NOT NULL,
    company_segment VARCHAR(100),
    customer_url_profile VARCHAR(200),
    company_icp TEXT,
    creation_date DATE DEFAULT CURRENT_DATE,
    last_update TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT companies_pkey PRIMARY KEY (id, company_name),
    CONSTRAINT companies_id_key UNIQUE (id)
);

CREATE INDEX IF NOT EXISTS companies_name_idx ON companies (company_name);
