CREATE TABLE "public"."auth_users" ( 
  "id" UUID NOT NULL DEFAULT uuid_generate_v4() ,
  "email" USER-DEFINED NOT NULL,
  "first_name" VARCHAR(120) NULL,
  "last_name" VARCHAR(120) NULL,
  "password_hash" TEXT NOT NULL,
  "last_login" TIMESTAMP WITH TIME ZONE NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() ,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() ,
  CONSTRAINT "auth_users_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "auth_users_email_key" UNIQUE ("email")
);
CREATE TABLE "public"."companies" ( 
  "id" INTEGER NOT NULL,
  "company_name" VARCHAR(200) NOT NULL,
  "company_url_profile" VARCHAR(200) NOT NULL,
  "company_segment" VARCHAR(100) NULL,
  "customer_url_profile" VARCHAR(200) NULL,
  "creation_date" DATE NULL,
  "last_update" DATE NULL,
  "company_icp" TEXT NULL,
  "icp_industries" ARRAY NULL,
  "icp_company_size" VARCHAR(50) NULL,
  "icp_target_country" VARCHAR(100) NULL,
  "icp_target_city" VARCHAR(120) NULL,
  "icp_industry_pain" TEXT NULL,
  "icp_competitors" ARRAY NULL,
  "icp_current_customers" ARRAY NULL,
  "buyer_persona_name" VARCHAR(150) NULL,
  "buyer_persona_age" INTEGER NULL,
  "buyer_persona_role" VARCHAR(150) NULL,
  "buyer_persona_company_type" VARCHAR(150) NULL,
  "buyer_persona_location" VARCHAR(150) NULL,
  "buyer_persona_goals" TEXT NULL,
  "buyer_persona_pain_points" TEXT NULL,
  "buyer_persona_buying_behavior" TEXT NULL,
  "buyer_persona_channels" ARRAY NULL,
  CONSTRAINT "companies_pkey" PRIMARY KEY ("id", "company_name"),
  CONSTRAINT "companies_id_key" UNIQUE ("id")
);
CREATE TABLE "public"."leads" ( 
  "id_lead" TEXT NOT NULL,
  "company_id" INTEGER NULL,
  "nombre" TEXT NULL,
  "cargo" TEXT NULL,
  "seniority" TEXT NULL,
  "rol_funcional" TEXT NULL,
  "empresa" TEXT NULL,
  "sector_empresa" TEXT NULL,
  "pais" TEXT NULL,
  "ciudad" TEXT NULL,
  "tamano_empresa_empleados" INTEGER NULL,
  "headline_perfil" TEXT NULL,
  "resumen_perfil" TEXT NULL,
  "temas_clave_publicaciones" ARRAY NULL DEFAULT '{}'::text[] ,
  "ultimas_publicaciones_texto" ARRAY NULL DEFAULT '{}'::text[] ,
  "interacciones_relevantes" ARRAY NULL DEFAULT '{}'::text[] ,
  "tags_internos" ARRAY NULL DEFAULT '{}'::text[] ,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() ,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() ,
  "linkedin_url" TEXT NULL,
  CONSTRAINT "leads_pkey" PRIMARY KEY ("id_lead"),
  CONSTRAINT "leads_linkedin_url_key" UNIQUE ("linkedin_url")
);
CREATE TABLE "public"."linkedin_leads" ( 
  "urn" TEXT NOT NULL,
  "profile_url" TEXT NULL,
  "profile_image" TEXT NULL,
  "full_name" TEXT NULL,
  "headline" TEXT NULL,
  "current_company" TEXT NULL,
  "company_urn" TEXT NULL,
  "company_description" TEXT NULL,
  "position_title" TEXT NULL,
  "industry" TEXT NULL,
  "location" TEXT NULL,
  "is_premium" BOOLEAN NOT NULL DEFAULT false ,
  "company_joined_at" TIMESTAMP WITH TIME ZONE NULL,
  "company_website" TEXT NULL,
  "posts_summary" TEXT NULL,
  "product_summary" TEXT NULL,
  "company_news" TEXT NULL,
  "company_post_summary" TEXT NULL,
  "lead_score" TEXT NULL,
  "contact_request" BOOLEAN NOT NULL DEFAULT false ,
  "connected" BOOLEAN NOT NULL DEFAULT false ,
  "message_sent" BOOLEAN NOT NULL DEFAULT false ,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() ,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() ,
  CONSTRAINT "linkedin_leads_pkey" PRIMARY KEY ("urn")
);
CREATE TABLE "public"."prospectos" ( 
  "id" SERIAL,
  "id_externo" TEXT NOT NULL,
  "nombre_completo" TEXT NULL,
  "email" TEXT NULL,
  "perfil_linkedin" TEXT NULL,
  "cargo" TEXT NULL,
  "about" TEXT NULL,
  "location" TEXT NULL,
  "estado" TEXT NULL,
  "fecha_creacion_origen" TIMESTAMP WITH TIME ZONE NULL,
  "company_id" INTEGER NULL,
  "company_origen_lead" TEXT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NULL DEFAULT now() ,
  "updated_at" TIMESTAMP WITH TIME ZONE NULL DEFAULT now() ,
  CONSTRAINT "prospectos_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "prospectos_id_externo_key" UNIQUE ("id_externo")
);
CREATE TABLE "public"."search_results_companies" ( 
  "company_id" INTEGER NOT NULL,
  "link" TEXT NOT NULL,
  "title" TEXT NULL,
  "redirect_link" TEXT NULL,
  "displayed_link" TEXT NULL,
  "source" TEXT NULL,
  "created_at" TIMESTAMP NULL DEFAULT now() ,
  CONSTRAINT "search_results_companies_pkey" PRIMARY KEY ("company_id", "link")
);
ALTER TABLE "public"."leads" ADD CONSTRAINT "leads_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies" ("id") ON DELETE SET NULL ON UPDATE NO ACTION;
